GET http://localhost:8000/products/?price_lt=200 HTTP/1.1

###
GET http://localhost:8000/products/2/ HTTP/1.1

###
DELETE http://localhost:8000/products/2/ HTTP/1.1

###
PUT http://localhost:8000/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI4Mzg1NDk2LCJpYXQiOjE3MjgzODUxOTYsImp0aSI6IjVkZTNjZGYxMzExZDQ4MmU5ZjVlN2E2M2FhNzQ3Y2IxIiwidXNlcl9pZCI6MX0.Lt7xSkdVv20Z-zn9rR2VrNn5n9rFdtlWR_xuT3jmP2Q

{
	"name": "Television",
	"price": 300.00,
	"stock": 14,
	"description": "An amazing new TV"    
}

###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0ODU1MjM1LCJpYXQiOjE3NzQ4NTQ5MzUsImp0aSI6IjcwZDVmYTcyYjlmMjQxZTE4ODdkY2EwZTBhM2I3OWJlIiwidXNlcl9pZCI6IjEifQ.HDuvVd1vP5AleR-rcmg17wio9RqAJODSu8vu6sAzxSg

{
	"name": "Television",
	"price": 300.00,
	"stock": 14,
	"description": "An amazing new TV"    
}

### 
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
	"username": "haile",
	"password": "12345678"
}

###
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
	"refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyODQwOTAzMSwiaWF0IjoxNzI4MzIyNjMxLCJqdGkiOiI3ZjdmZDExNDhjZTg0Njk5YTdiYmY2OWZlNmRiMzczYSIsInVzZXJfaWQiOjF9.KRzvCrbOC_XbxFqjGWf9iTf4lhlnWAdddfCjp7dPrFM"
}

###
POST http://localhost:8000/register/ HTTP/1.1
Content-Type: application/json

{
	"username": "newuser",
	"password": "newpassword123"
}

###
POST http://localhost:8000/register/ HTTP/1.1
Content-Type: application/json

{
    "username": "haileMichael",
    "password": "12345678",
    "email": "haileMichael@gmail.com"
}

###

GET http://localhost:8000/users/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0OTU4MjY0LCJpYXQiOjE3NzQ5NTc5NjQsImp0aSI6ImVmNjEwOTMzOTMyMTRiNDQ5ZDkxZWM4ZDEzZjEyMzdmIiwidXNlcl9pZCI6IjEifQ.KnaeOmOX4OGWABCcosGlaYZ9shNsnbEPWjKuBeZloT0

###
POST http://localhost:8000/orders/create/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0ODYwODE0LCJpYXQiOjE3NzQ4NjA1MTQsImp0aSI6IjYzMTBjMGQ5MzhmNzRlZTM5Y2U1OGNmZTVjM2UxMTg3IiwidXNlcl9pZCI6IjIifQ.t3hMliHNGp7sYGz_ZI8Ci7X0WmPiCIC3XhcEUoW9Uyk

{
    "items": [
        {
            "product": 1,
            "quantity": 1
        }
    ]
}

###
GET http://localhost:8000/orders/listOrders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0OTYwNTQ1LCJpYXQiOjE3NzQ5NjAyNDUsImp0aSI6IjY2MmE2ZGJjNTY4ZTRkNDRiZGE1MWY1MGYxMWMwYjYyIiwidXNlcl9pZCI6IjEifQ.sosut3ze-9JYGR5dkCQ9XFjoE1i7USEJBCcjnIjZKL4


###
GET http://localhost:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0OTU4MzQxLCJpYXQiOjE3NzQ5NTgwNDEsImp0aSI6Ijk1ZWJmN2JmN2IyYzRiYTJiOTU0NjFmNmFjZjhmZDkxIiwidXNlcl9pZCI6IjIifQ.fngir5q6BpFlNexcQhQShKbZHvaWPhboMyGs4aMjbPY


###
PATCH http://localhost:8000/orders/6a37366c-7e3d-4cfb-9280-165766ab3184/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0OTYyMjA0LCJpYXQiOjE3NzQ5NjE5MDQsImp0aSI6Ijg3NTYyODU3YTgxNTQ1M2I5NDYxOWQ3ZDYyMTAzZTAyIiwidXNlcl9pZCI6IjEifQ.nRBRLy_K4Lcc-qb8pp2KZDmRKmvqe9_RKPZ9TfLr1aY

{   
    "status": "Cancelled"
}

###
DELETE http://localhost:8000/orders/1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0OTYwMjcyLCJpYXQiOjE3NzQ5NTk5NzIsImp0aSI6ImU4YTQ5NjBhZDI5MjQ2YzE5ZWU0YWE1NGY1YWU3YzMzIiwidXNlcl9pZCI6IjEifQ.hxBIEq3H2rG2pH3fAqTTrd8QKaaQoWKyps1RA36wS6w